apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  labels:
    app: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console
          image: quay.io/eranra/network-observability-console-plugin-standalone:dev
          command: ["/bin/sh", "-c", "./plugin-backend --auth-check none --frontend-config /etc/console/config.yaml --loglevel trace --loki http://loki:3100"]
          ports:
            - containerPort: 9001
          volumeMounts:
            - name: configuration
              mountPath: "/etc/console/"
      volumes:
        - name: configuration
          configMap:
            name: console-configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-configuration
data:
  config.yaml: |
    recordTypes:
      - flowLog
    portNaming:
      enable: true
      portNames:
        "3100": loki
    quickFilters:
      - name: MultiCluster
        filter:
          src_kind: 'Pod,Service'
          dst_kind: 'Pod,Service'
          src_namespace: 'east,west'
        default: true
      - name: Applications
        filter:
          src_namespace!: 'openshift-,netobserv'
          dst_namespace!: 'openshift-,netobserv'
      - name: Infrastructure
        filter:
          src_namespace: 'openshift-,netobserv'
          dst_namespace: 'openshift-,netobserv'
      - name: Pods network
        filter:
          src_kind: 'Pod'
          dst_kind: 'Pod'
        default: true
      - name: Services network
        filter:
          dst_kind: 'Service'
    alertNamespaces:
      - netobserv
    sampling: 1  
---
apiVersion: v1
kind: Service
metadata:
  name: console
  labels:
    app: console
spec:
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: console
  selector:
    app: console
---

